// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DescribeGrpcSymbol(arg1:string,arg2:string):Promise<string>;

export function GetGrpcMessageTemplate(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InvokeGrpc(arg1:string,arg2:string,arg3:{[key: string]: any},arg4:{[key: string]: any}):Promise<backend.CommonResp>;

export function ListGrpcSymbol(arg1:string,arg2:string):Promise<Array<string>>;
